# Generated by Django 3.0.8 on 2020-07-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_year_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
