# Generated by Django 3.0.8 on 2020-07-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_cars_car_year_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_forsale',
            field=models.BooleanField(default=False),
        ),
    ]
