# Generated by Django 3.0.8 on 2020-07-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_cars_car_forsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
