# Generated by Django 3.0.8 on 2020-07-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_cars_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_headline',
            field=models.CharField(default='', max_length=100),
        ),
    ]
