# Generated by Django 3.0.8 on 2020-07-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_cars_car_boughtat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_boughtat',
            field=models.DateTimeField(),
        ),
    ]
