# Generated by Django 3.0.8 on 2020-07-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20200719_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_forsale',
            field=models.CharField(default='off', max_length=5),
        ),
    ]
