# Generated by Django 3.0.8 on 2020-07-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20200721_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_rank',
            field=models.IntegerField(default=0),
        ),
    ]
