# Generated by Django 3.0.8 on 2020-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20200729_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_power',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_rank',
            field=models.IntegerField(default=1),
        ),
    ]
