# Generated by Django 3.0.8 on 2020-07-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20200729_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_hp',
            field=models.IntegerField(default=0),
        ),
    ]
