# Generated by Django 3.0.8 on 2020-07-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_cars_car_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_headline',
            field=models.CharField(default='', max_length=200),
        ),
    ]
